[package]
name = "rust-socket-demo1"
version = "0.1.0"
edition = "2021"

[dependencies]
rust_socketio = { version = "^0.6.0", features = ["async"] }
tokio = { version = "1.37.0", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
futures-util = "0.3.30"
